
[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deduplic"
version = "0.1.0"
description = "Python library and CLI for deduplicating records in JSON files."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Gabriel David Moreno Reyes" }
]
#IN CASE OF PUBLICATION
# classifiers = [
#     "Programming Language :: Python :: 3",
#     "Operating System :: OS Independent",
# ]
dependencies = [
    "scikit-learn>=1.3.0",
    "scipy>=1.11.0",
    "numpy>=1.24.0",
    "platformdirs>=4.0.0",
]

[project.optional-dependencies]
gui = [
    "streamlit>=1.30.0",
    "diff-match-patch>=20230505",
]
dev = [
    "pytest>=7.0"
]

[project.scripts]
deduplic_init = "deduplic.cli_cmds.cmd_deduplic_init_from_file:main"
deduplic_connection = "deduplic.cli_cmds.cmd_deduplic_connection:main"
deduplic_cluster = "deduplic.cli_cmds.cmd_deduplic_cluster:main"
deduplic_cluster_by_id = "deduplic.cli_cmds.cmd_deduplic_cluster_by_id:main"
deduplic_all = "deduplic.cli_cmds.cmd_deduplic_all:main"
deduplic_deduplic_get_state = "deduplic.cli_cmds.cmd_deduplic_get_state:main"
deduplic_commit = "deduplic.cli_cmds.cmd_deduplic_commit:main"
deduplic_restore = "deduplic.cli_cmds.cmd_deduplic_restore:main"
deduplic_delete_project = "deduplic.cli_cmds.cmd_delete_project:main"
deduplic_delete_all = "deduplic.cli_cmds.cmd_delete_all:main"
deduplic_exec_merges = "deduplic.cli_cmds.cmd_deduplic_exec_merge:main"
deduplic_list_pending_merges = "deduplic.cli_cmds.cmd_deduplic_list_pending_merges:main"
deduplic_has_pending_merges = "deduplic.cli_cmds.cmd_deduplic_has_pending_merges:main"
deduplic_forget_single_merge = "deduplic.cli_cmds.cmd_deduplic_forget_single_merge:main"
deduplic_forget_merges = "deduplic.cli_cmds.cmd_deduplic_forget_merges:main"
deduplic_set_workspace_dir = "deduplic.cli_cmds.cmd_deduplic_set_workspace_dir:main"
deduplic_purge_workspace = "deduplic.cli_cmds.cmd_deduplic_purge_workspace:main"
deduplic_gui = "deduplic.cli_cmds.cmd_deduplic_launch_gui:run_gui"

[tool.setuptools.packages.find]
where = ["src"]